CREATE DATABASE myfirstlogin;

GRANT ALL ON DATABASE myfirstlogin TO postgres;
GRANT CONNECT ON DATABASE myfirstlogin TO webapp;

CREATE TABLE mfl_user (
    user_id SERIAL NOT NULL PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    hash VARCHAR(128) NOT NULL,
    fullname VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL
);

GRANT USAGE ON SCHEMA public TO webapp;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO webapp;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO webapp;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO webapp;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO webapp;
