-- Nuevo nombre del aplicativo móvil
INSERT INTO MYFIRSTLOGIN.MFL_APLICACION (NOMBRE) VALUES ('MFL_MOBILE');

-- Antiguo nombre del aplicativo móvil
INSERT INTO MYFIRSTLOGIN.MFL_APLICACION (NOMBRE) VALUES ('MY_FIRST_LOGIN');
