-- Nuevo nombre del aplicativo móvil
INSERT INTO MYFIRSTLOGIN.MFL_APLICACION (NOMBRE, FECHA_CREACION, USUARIO_CREACION) VALUES ('MFL_MOBILE', NOW(), 'agutierrez');

-- Antiguo nombre del aplicativo móvil
INSERT INTO MYFIRSTLOGIN.MFL_APLICACION (NOMBRE, FECHA_CREACION, USUARIO_CREACION) VALUES ('MY_FIRST_LOGIN', NOW(), 'agutierrez');
